/* tslint:disable */
/* eslint-disable */
/**
 * DeltaStream REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime.ts';
/**
 *
 * @export
 * @interface Organization
 */
export interface Organization {
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  organizationID: string;
  /**
   *
   * @type {string}
   * @memberof Organization
   */
  defaultRoleName: string;
  /**
   *
   * @type {Array<string>}
   * @memberof Organization
   */
  grantedRoles?: Array<string>;
  /**
   *
   * @type {Array<string>}
   * @memberof Organization
   */
  inheritedRoles?: Array<string>;
}

/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'organizationID' in value;
  isInstance = isInstance && 'defaultRoleName' in value;

  return isInstance;
}

export function OrganizationFromJSON(json: any): Organization {
  return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Organization {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    organizationID: json['organizationID'],
    defaultRoleName: json['defaultRoleName'],
    grantedRoles: !exists(json, 'grantedRoles')
      ? undefined
      : json['grantedRoles'],
    inheritedRoles: !exists(json, 'inheritedRoles')
      ? undefined
      : json['inheritedRoles'],
  };
}

export function OrganizationToJSON(value?: Organization | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    organizationID: value.organizationID,
    defaultRoleName: value.defaultRoleName,
    grantedRoles: value.grantedRoles,
    inheritedRoles: value.inheritedRoles,
  };
}
