/* tslint:disable */
/* eslint-disable */
/**
 * DeltaStream Dataplane REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ResultSetDataInnerInner } from './ResultSetDataInnerInner';
import {
  ResultSetDataInnerInnerFromJSON,
  ResultSetDataInnerInnerFromJSONTyped,
  ResultSetDataInnerInnerToJSON,
} from './ResultSetDataInnerInner';
import type { ResultSetMetadata } from './ResultSetMetadata';
import {
  ResultSetMetadataFromJSON,
  ResultSetMetadataFromJSONTyped,
  ResultSetMetadataToJSON,
} from './ResultSetMetadata';

/**
 *
 * @export
 * @interface ResultSet
 */
export interface ResultSet {
  /**
   *
   * @type {string}
   * @memberof ResultSet
   */
  sqlState: string;
  /**
   *
   * @type {string}
   * @memberof ResultSet
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof ResultSet
   */
  statementID: string;
  /**
   * UTC POSIX timestamp of when statement was submitted
   * @type {number}
   * @memberof ResultSet
   */
  createdOn: number;
  /**
   *
   * @type {ResultSetMetadata}
   * @memberof ResultSet
   */
  metadata: ResultSetMetadata;
  /**
   * Each item within a column of data is expressed as a string, regardless of the DeltaStream type of the column.
   * For example, the number 1.0 will be returned as "1.0".
   * @type {Array<Array<ResultSetDataInnerInner>>}
   * @memberof ResultSet
   */
  data?: Array<Array<ResultSetDataInnerInner>>;
}

/**
 * Check if a given object implements the ResultSet interface.
 */
export function instanceOfResultSet(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'sqlState' in value;
  isInstance = isInstance && 'statementID' in value;
  isInstance = isInstance && 'createdOn' in value;
  isInstance = isInstance && 'metadata' in value;

  return isInstance;
}

export function ResultSetFromJSON(json: any): ResultSet {
  return ResultSetFromJSONTyped(json, false);
}

export function ResultSetFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ResultSet {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sqlState: json['sqlState'],
    message: !exists(json, 'message') ? undefined : json['message'],
    statementID: json['statementID'],
    createdOn: json['createdOn'],
    metadata: ResultSetMetadataFromJSON(json['metadata']),
    data: !exists(json, 'data') ? undefined : json['data'],
  };
}

export function ResultSetToJSON(value?: ResultSet | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sqlState: value.sqlState,
    message: value.message,
    statementID: value.statementID,
    createdOn: value.createdOn,
    metadata: ResultSetMetadataToJSON(value.metadata),
    data: value.data,
  };
}
