/* tslint:disable */
/* eslint-disable */
/**
 * DeltaStream Dataplane REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResultSetColumnsInner
 */
export interface ResultSetColumnsInner {
    /**
     * 
     * @type {string}
     * @memberof ResultSetColumnsInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ResultSetColumnsInner
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof ResultSetColumnsInner
     */
    nullable: boolean;
}

/**
 * Check if a given object implements the ResultSetColumnsInner interface.
 */
export function instanceOfResultSetColumnsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "nullable" in value;

    return isInstance;
}

export function ResultSetColumnsInnerFromJSON(json: any): ResultSetColumnsInner {
    return ResultSetColumnsInnerFromJSONTyped(json, false);
}

export function ResultSetColumnsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResultSetColumnsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'nullable': json['nullable'],
    };
}

export function ResultSetColumnsInnerToJSON(value?: ResultSetColumnsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'type': value.type,
        'nullable': value.nullable,
    };
}

