name: CI
on:
  push:
    branches:
      - main
  pull_request_target:
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
