name: Publish
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - run: |-
          pnpm changeset status --verbose | tee /tmp/summary

      - run: pnpm changeset version

      - uses: actions/github-script@v7
        id: create-pr-branch
        name: Create PR branch
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              try {
                await github.rest.git.createRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'refs/heads/version-packages',
                  sha: '${{ github.sha }}'
                });
              } catch (error) {
                await github.rest.git.updateRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: 'heads/version-packages',
                  sha: '${{ github.sha }}',
                  force: true
                });
              }

      - uses: planetscale/ghcommit-action@v0.1.6
        with:
          commit_message: "Version packages"
          repo: ${{ github.repository }}
          branch: "version-packages"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - uses: actions/github-script@v7
        id: create-pr
        name: Create PR
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('/tmp/summary', 'utf-8');

            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Version packages',
              head: 'version-packages',
              base: 'main',
              body: '```' + body + '```'
            });
